#!/bin/bash
#PBS -j eo
#PBS -l nodes=1

export RUNID=`echo ${PBS_JOBID} | sed -e 's/.rigi//'`
export SCRATCHDIR=/scratch/${USER}/${RUNID}

module load XE2016.0.3.210

mkdir -p ${SCRATCHDIR}
cd ${PBS_O_WORKDIR}

cp RHF.py ${SCRATCHDIR} 
cp FCIDUMP ${SCRATCHDIR}
cd ${SCRATCHDIR}

${PBS_O_WORKDIR}/job.py> ${PBS_O_WORKDIR}/RHF.out

rm -rf ${SCRATCHDIR}



